### ISSUE TITLE
Dependency Required

### ISSUE THREAD

**Issue by luckyxu** [Strumenta/sas-parser-samples#2]
<dependency>
            <groupId>com.strumenta.langmodules.sas-parser</groupId>
            <artifactId>ast</artifactId>
            <version>${project.version}</version>
</dependency>

How can I get this dependency and run the sample?

**Comment by ftomassetti** [comment]
Hello @luckyxu , you contacted us also by email, and we continued the discussion there, however I will reply also here in case someone ready this issue in the future.

This particular project demonstrates the capabilities of our SAS Parser. However the SAS Parser itself is a commercial product, so it is available only for those who acquire a license from us.
